apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculator-app.name" . }}
  labels:
    {{- include "calculator-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "calculator-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calculator-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "calculator-app.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
